config/routes.rb
Rails.application.routes.draw do
  resources :courses do
   member do
   get :roll
  end
end

  resources :awards

  resources :students do
    member do
    get :courses
    post :course_add
    post :course_remove  
    end
  end

end

app/models/award.rb
class Award < ActiveRecord::Base
	belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_and_belongs_to_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :awards
	has_and_belongs_to_many :courses

	def enrolled_in?(course)
		self.courses.include?(course)
	end
	def unenrolled_courses
		Course.all - self.courses
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :set_award, only: [:show, :edit, :update, :destroy]

  # GET /awards
  # GET /awards.json
  def index
    @awards = Award.all
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
  end

  # GET /awards/new
  def new
    @award = Award.new
    @students = Student.all

  end

  # GET /awards/1/edit
  def edit
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = Award.new(award_params)

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render :show, status: :created, location: @award }
      else
        format.html { render :new }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awards/1
  # PATCH/PUT /awards/1.json
  def update
    respond_to do |format|
      if @award.update(award_params)
        format.html { redirect_to @award, notice: 'Award was successfully updated.' }
        format.json { render :show, status: :ok, location: @award }
      else
        format.html { render :edit }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award.destroy
    respond_to do |format|
      format.html { redirect_to awards_url, notice: 'Award was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_award
      @award = Award.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def award_params
      params.require(:award).permit(:name, :name, :year, :student_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  #GET /courses/1/roll
  def roll
    @course = Course.find(params[:id])
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  #GET /students/1/courses
  def courses
    @student = Student.find(params[:id])
    @courses = @student.courses
  end

  # POST /students/1/course_add?course_id=2
  # (note no real query string, just
  # convenient notation for parameters)
  def course_add
    #convert ids from routing to objects
    @student = Student.find(params[:id])
    @course = Course.find(params[:course])

    if not @student.enrolled_in?(@course)
      #add course to list using  << operator
      @student.courses << @course
      flash[:notice] = 'Student was successfully enrolled'
    else
      flash[:error] = 'Student was already enrolled'
    end
    redirect_to :action => :courses, :id => @student
  end

  # POST /students/1/course_remove?courses[]=
def course_remove
  #Convert ids from routing to object
  @student = Student.find(params[:id])
  #get list of courses to remove from query string
  course_ids = params[:courses]
  unless course_ids.blank?
    course_ids.each do |course_id|
      course = Course.find(course_id)
      if @student.enrolled_in?(course)
        logger.info "Removing student from course #{course.id}"
        @student.courses.delete(course)
        flash[:notice] = 'Course was successfully deleted'
      end
    end
  end
  redirect_to :action => :courses, :id => @student
end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:given_name, :middle_name, :family_name, :date_of_birth, :grade_point_average, :start_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/application/_navigation.html.erb
<p>
  <%= link_to "Students", students_url %> |
  <%= link_to "Courses", courses_url %>
</p>
<hr />

app/views/awards/_form.html.erb
<%= form_for(@award) do |f| %>
  <% if @award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% @award.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
 
  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.select :student_id, Student.all.collect {|s| [(s.given_name + " " + s.family_name), s.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<h1>Editing award</h1>

<%= render 'form' %>

<%= link_to 'Show', @award %> |
<%= link_to 'Back', awards_path %>

app/views/awards/index.html.erb
<h1>Listing awards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Name</th>
      <th>Year</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @awards.each do |award| %>
      <tr>
        <td><%= award.name %></td>
        <td><%= award.name %></td>
        <td><%= award.year %></td>
        <td><%= award.student_id %></td>
        <td><%= link_to 'Show', award %></td>
        <td><%= link_to 'Edit', edit_award_path(award) %></td>
        <td><%= link_to 'Destroy', award, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Award', new_award_path %>

app/views/awards/new.html.erb
<h1>New award</h1>

<%= render 'form' %>

<%= link_to 'Back', awards_path %>

app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @award.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @award.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @award.year %>
</p>

<p>
  <strong>Student:</strong>
  <%= @award.student_id %>
</p>

<%= link_to 'Edit', edit_award_path(@award) %> |
<%= link_to 'Back', awards_path %>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Enrolled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.students.count %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/roll.html.erb
<h1>Roll for <%= @course.name %></h1>
<% if @course.students.count > 0 %>
  <table>
    <tr>
      <th>Student</th>
      <th>GPA</th>
    </tr>
    <% for student in @course.students do %>
      <tr>
        <td><%=link_to student.given_name, student %></td>
        <td><%= student.grade_point_average %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>No students are enrolled.</p>
<% end %>
<p><%= link_to "Back", @course %></p>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>
<%= link_to 'Roll', roll_course_path(@course) %>
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Students</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'navigation' %>
<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :given_name %><br>
    <%= f.text_field :given_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :family_name %><br>
    <%= f.text_field :family_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :grade_point_average %><br>
    <%= f.text_field :grade_point_average %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/courses.html.erb
<h1><%= @student.given_name %>'s courses</h1>
<% if @courses.length > 0 %>
  <%= form_tag(course_remove_student_path(@student)) do %>
  <table>
    <tr>
      <th>Course</th>
      <th>Remove?</th>
    </tr>
  <% for course in @courses do %>
    <tr>
      <td><%= course.name %></td>
      <td><%= check_box_tag "courses[]", course.id %></td>
    </tr>
  <% end %>
  </table>
  <br />
  <%= submit_tag 'Remove checked courses' %>
  <% end %>
<% else %>
  <p>Not enrolled in any courses yet.</p>
<% end %>
<h2>Enroll in new course</h2>
<% if @student.courses.count < Course.count then %>
  <%= form_tag(course_add_student_path(@student)) do %>
    <%= select_tag(:course,
      options_from_collection_for_select(@student.unenrolled_courses,
        :id, :name)) %>
    <%= submit_tag 'Enroll' %>
  <% end %>
<% else %>
  <p><%= @student.given_name %> is enrolled in every course.</p>
<% end %>
<p><%=link_to "Back", @student %></p>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Given name</th>
      <th>Middle name</th>
      <th>Family name</th>
      <th>Date of birth</th>
      <th>Grade point average</th>
      <th>Courses</th>
      <th>Start date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.given_name %></td>
        <td><%= student.middle_name %></td>
        <td><%= student.family_name %></td>
        <td><%= student.date_of_birth %></td>
        <td><%= student.grade_point_average %></td>
        <td><%= student.courses.count %></td>
        <td><%= student.start_date %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Given name:</strong>
  <%= @student.given_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @student.middle_name %>
</p>

<p>
  <strong>Family name:</strong>
  <%= @student.family_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @student.date_of_birth %>
</p>

<p>
  <strong>Grade point average:</strong>
  <%= @student.grade_point_average %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @student.start_date %>
</p>

<p>
  <b>Courses:</b>
  <% if !@student.courses.empty? %>
    <%= @student.courses.collect {|c| link_to(c.name, c)}.join(", ").html_safe%>
  <% else %>
    Not enrolled on any courses yet.
  <% end %>
</p>

<%= link_to 'Courses', courses_student_path(@student) %> |
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>